name: juneau
description: juneau mobile application
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_check: ^1.0.1
  cupertino_icons: ^1.0.2
  dots_indicator: ^1.2.0
  edge_alert: ^0.0.1
  email_validator: ^1.0.0
  flutter_absolute_path: ^1.0.6
  http: ^0.12.0+4
  keyboard_visibility: ^0.5.6
  multi_image_picker: ^4.7.10
  path: ^1.7.0
  pull_to_refresh: ^1.6.4
  rxdart: ^0.25.0
  scrollable_positioned_list: ^0.1.9
  shared_preferences: ^0.5.8
  timeago: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/